-bad
-bap
-nbc
-br
-cdb
-nce
-ci3
-cli3
-di12
-dj
-ei
-fc1
-i3
-l72
-lp
-npcs
-psl
-sc
-sob
-TBlock -TBlockHeap -TClass -Tdbuf -Tdbufbuf -TaConfList -TaConfEntry
-Tfdstruct -Thashentry -Treslist -Tcache -Tcachetable -TaConfItem
-TaClient -TaChannel -TanUser -TaServer -TLink -TMode -Tts_val
-TaMotd -TWhowas -Tmsg_tree -TBan -Tu_char -Tu_short -Tu_long
-Tu_int -Taname -THEADER -Tip_entry -Tgline_pending -Tscache_entry
-TNumeric
