#!/usr/bin/env python3
"""Generate src/version.c for the bahamut IRC server.

Called by the Meson build system as a custom_target.
Usage: gen_version.py <output_file> <source_root>
"""

import os
import subprocess
import sys
from datetime import datetime, timezone

def read_generation(last_file):
    if not os.path.exists(last_file):
        return 0
    with open(last_file) as f:
        for line in f:
            if line.startswith('char *generation'):
                try:
                    return int(line.split('"')[1])
                except (IndexError, ValueError):
                    pass
    return 0

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output_file> <source_root>", file=sys.stderr)
        sys.exit(1)

    output_file = sys.argv[1]
    source_root = sys.argv[2]
    last_file   = os.path.join(source_root, 'src', 'version.c.last')

    generation = read_generation(last_file) + 1

    try:
        uname = subprocess.check_output(['uname', '-a'], text=True).strip()
    except Exception:
        uname = 'unknown'

    creation = datetime.now(timezone.utc).strftime('%a %b %d %Y at %H:%M:%S UTC')

    content = f'''\
/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This file is generated by gen_version.py — do not edit by hand.
 */

#include "struct.h"
#include "patchlevel.h"

char *generation = "{generation}";
char *creation   = "{creation}";
char  version[128];

char *infotext[] =
{{
    "bahamut --",
    "Based on the original code written by Jarkko Oikarinen",
    "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
    "",
    "This program is free software; you can redistribute it and/or",
    "modify it under the terms of the GNU General Public License as",
    "published by the Free Software Foundation; either version 1, or",
    "(at your option) any later version.",
    "",
    "Regular expression support is provided by the PCRE library package,",
    "which is open source software, written by Philip Hazel, and copyright",
    "by the University of Cambridge, England.",
    "",
    "Report security bugs to coders@dal.net",
    "Report other bugs at https://github.com/DALnet/bahamut/issues",
    "",
    0,
}};
'''

    with open(output_file, 'w') as f:
        f.write(content)

    # Keep a copy so the generation counter survives across builds
    with open(last_file, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    main()
