name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build libssl-dev
    - name: configure
      run: ./configure
    - name: setup
      run: meson setup build -Dhookmodules=true
    - name: build
      run: ninja -C build
